# Generated by Django 5.2.8 on 2025-12-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_like_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like',
            new_name='is_like',
        ),
    ]
